### ISSUE TITLE
Does not build in MSYS2/MinGW, GCC 13.1: sys/mman.h not found

### ISSUE THREAD

**Issue by LigH-de** [abique/midi-parser#13]
Hi. I am not an experienced C developer, just a halfwit able to run the [media-autobuild suite](https://github.com/m-ab-s/media-autobuild_suite) to build ffmpeg and related linked projects, and interpreting error messages when anything fails.

Here I tried to use an interactive MinGW shell to build your midi-parser. I learned that the file **mman.h** does not exist by default in an MSYS2 installation, so I installed the package `msys2-runtime-devel`. Now I have the file `/usr/include/sys/mman.h`. Yet it seems not to be included by default in the includes paths, which confuses me.

BTW, running `cmake .` generates a ninja build script in the MSYS2 environment of MABS, but that should be quite equal to a makefile.
```
$ ninja
[1/2] Building C object CMakeFiles/midi-dump.dir/example/midi-dump.c.obj
FAILED: CMakeFiles/midi-dump.dir/example/midi-dump.c.obj
G:\MABS\msys64\mingw64\bin\ccache.exe  gcc  -IG:/MABS/build/midi-parser-master/include -fstack-protector-strong -mtune=generic -O2 -pipe -mthreads -std=gnu99 -MD -MT CMakeFiles/midi-dump.dir/example/midi-dump.c.obj -MF CMakeFiles\midi-dump.
dir\example\midi-dump.c.obj.d -o CMakeFiles/midi-dump.dir/example/midi-dump.c.obj -c G:/MABS/build/midi-parser-master/example/midi-dump.c
G:/MABS/build/midi-parser-master/example/midi-dump.c:3:10: fatal error: sys/mman.h: No such file or directory
    3 | #include <sys/mman.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
I wonder if I should help cmake finding include paths by adding parameters, but I have no clue which would be appropriate.

[midi-parser-logs.zip](https://github.com/abique/midi-parser/files/12064148/midi-parser-logs.zip)

**Comment by LigH-de** [comment]
I hope @1480c1 may have an idea.

**Comment by 1480c1** [comment]
Windows lacks mmap, but does provide its own way of creating a memory map of a file <https://learn.microsoft.com/en-us/windows/win32/memory/creating-a-view-within-a-file>

@LigH-de, when compiling stuff with mingw-w64, you are only allowed to use system includes from /mingw64, or whatever $MINGW_PREFIX is, gcc and clang should not automatically look under /usr/include as that's for the cygwin-based msys environment.

**Comment by LigH-de** [comment]
Thanks for this enlightenment. I have a separate cygwin environment too, maybe I will try to compile it there.

@abique - your decision to close as "Won't fix" or any other result.

**Comment by abique** [comment]
Hi,

Sorry I don't have time to work on this right now, but if you make a PR, I could merge it.

Cheers,
Alex
